group=com.rsicarelli
version=0.1.0-SNAPSHOT

POM_NAME=KMP Targets
POM_DESCRIPTION=Dynamically select which Kotlin Multiplatform targets to build via the kmptargets.targets Gradle property.
POM_INCEPTION_YEAR=2026
POM_URL=https://github.com/rsicarelli/kmp-targets/
POM_LICENCE_NAME=The Apache Software License, Version 2.0
POM_LICENCE_URL=https://www.apache.org/licenses/LICENSE-2.0.txt
POM_LICENCE_DIST=repo
POM_SCM_URL=https://github.com/rsicarelli/kmp-targets/
POM_SCM_CONNECTION=scm:git:git://github.com/rsicarelli/kmp-targets.git
POM_SCM_DEV_CONNECTION=scm:git:ssh://git@github.com/rsicarelli/kmp-targets.git
POM_DEVELOPER_ID=rsicarelli
POM_DEVELOPER_NAME=Rodrigo Sicarelli
POM_DEVELOPER_URL=https://github.com/rsicarelli

org.gradle.jvmargs=-Xmx2g -XX:+UseG1GC
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.parallel=true

kotlin.code.style=official
