[versions]
kotlin = "2.3.21"
junit = "6.1.0"
ktfmt = "0.26.0"
asm = "9.8"
mavenPublish = "0.35.0"

[libraries]
kotlin-gradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-gradlePluginApi = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin-api", version.ref = "kotlin" }
asm = { module = "org.ow2.asm:asm", version.ref = "asm" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ktfmt = { id = "com.ncorti.ktfmt.gradle", version.ref = "ktfmt" }
mavenPublish = { id = "com.vanniktech.maven.publish", version.ref = "mavenPublish" }
